version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
    env_file:
      - secrets.env
      - common.env

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    env_file:
      - common.env

  app:
    build: .
    image: nextcloud_vleon1:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - root:/var/www/html
      - data:/var/www/html/data
      - config:/var/www/html/config
      - custom_apps:/var/www/html/custom_apps
      - themes:/var/www/html/themes
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.vaiman.info 192.168.1.34
      - NEXTCLOUD_UPDATE=1
    env_file:
      - secrets.env
      - common.env
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:
  root:
  data:
  config:
  custom_apps:
  themes:
